<a href="https://colab.research.google.com/github/chanhee922/DeepLearning_Practice/blob/master/%EB%8B%A8%EC%B8%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EA%B5%AC%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 단층신경망 구성

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint as pp

In [0]:
class SingleLayer:
    
    def __init__(self):
        self.w = None
        self.b = None
        self.losses = []

    def forpass(self, x):
        z = np.sum(x * self.w) + self.b  # 직선 방정식을 계산합니다
        return z

    def backprop(self, x, err):
        w_grad = x * err    # 가중치에 대한 그래디언트를 계산합니다
        b_grad = 1 * err    # 절편에 대한 그래디언트를 계산합니다
        return w_grad, b_grad

    def activation(self, z):
        z = np.clip(z, -100, None) # 안전한 np.exp() 계산을 위해
        a = 1 / (1 + np.exp(-z))  # 시그모이드 계산
        return a
        
    def fit(self, x, y, epochs=100):
        self.w = np.ones(x.shape[1])               # 가중치를 초기화합니다.
        self.b = 0                                 # 절편을 초기화합니다.
        for i in range(epochs):                    # epochs만큼 반복합니다
            loss = 0
            # 인덱스를 섞습니다
            indexes = np.random.permutation(np.arange(len(x)))
            for i in indexes:                      # 모든 샘플에 대해 반복합니다
                z = self.forpass(x[i])             # 정방향 계산
                a = self.activation(z)             # 활성화 함수 적용
                err = -(y[i] - a)                  # 오차 계산
                w_grad, b_grad = self.backprop(x[i], err) # 역방향 계산
                self.w -= w_grad                   # 가중치 업데이트
                self.b -= b_grad                   # 절편 업데이트
                # 안전한 로그 계산을 위해 클리핑한 후 손실을 누적합니다
                a = np.clip(a, 1e-10, 1-1e-10)
                loss += -(y[i]*np.log(a)+(1-y[i])*np.log(1-a))
            # 에포크마다 평균 손실을 저장합니다
            self.losses.append(loss/len(y))
    
    def predict(self, x):
        z = [self.forpass(x_i) for x_i in x]     # 정방향 계산
        return np.array(z) > 0                   # 스텝 함수 적용
    
    def score(self, x, y):
        return np.mean(self.predict(x) == y)

In [0]:
class LogisticNeuron:
    
    def __init__(self):
        self.w = None
        self.b = None

        self.losses = [] # 손실함수의 오차값을 매 훈련시 마다 저장

        pass # constructor


    def forpass(self, x): # 정방향 계산
        # z = w1x1 + w2x2 + ... wixi + b
        z = np.sum(x * self.w) + self.b
        return z

        pass # forpass

    # 역방향 계산(오차역전파와 손실함수의 미분을 통한 가중치와 절편의 변화율 계산)
    def backprop(self, x, err): 
        w_grad = x * err        # 가중치(w)에 대한 변화율(gradient) 계산
        b_grad = 1 * err        # 절편(b)에 대한 변화율(gradient) 계산

        return w_grad, b_grad
        pass # backprop
    

    def activation(self, z):    # 활성화 함수(시그모이드)를 통과하여 반환
        # *** 안전한 지수(또는 로그) 계산을 위해 지정된 범위값을 가지도록 만듦
        z = np.clip(z, -100, None)
        a = 1 / (1 + np.exp(-z))

        return  a
        pass # activation


    # 신경망 훈련을 통한 최적의 가중치(w)와 절편(b)를 찾아가도록 훈련
    # (학습 = 손실함수에대한 미분)
    def fit(self, x, y, epochs = 100):
        
        # 1) 가중치와 절편의 초기값 설정
        self.w = np.ones(x.shape[1])    # x.shape[1] = 열(특성, 노드)의 개수
        self.b = 0

        # 2) epoch
        for i in range(epochs):
            loss = 0
            # 3) 전체 샘플을 활용한 학습(가중치/절편의 업데이트) 수행
            # 신경망을 훈련시킬 훈련 데이터 셋은 매 에포크마다 섞어야함
            # 전체 sample을 무작위로 섞는 함수: np.random.permutation()

            indexes = np.arange( len(x) )               # 전체 샘플의 인덱스 번호를 1차원 벡터로 생성
            indexes = np.random.permutation( indexes )  # 셔플링 후 다시 저장

            # 매 epoch 마다 평균 손실값의 오차를 계산
            self.losses = 0

            for i in indexes:
            # for xi, yi in zip(x, y):
                xi = x[i]       # i 번째 샘플의 입력 데이터
                yi = y[i]       # i 번째 샘플의 정답 데이터



                # 4) 정방향 계산 수행
                z = self.forpass(xi)
                
                # 5) 활성화 함수 통과
                a = self.activation(z)
                
                # 6) 오차계산
                err = -(yi - a)
                pass # training loop(1 epoch)

                # 7) 오차역전파를 통한 가중치와 절편의 변화율 계산
                w_grad, b_grad = self.backprop(xi, err)

                # 8) 계산된 가중치와 절편의 변화율을 이용한 가중치/절편 업데이트
                self.w -= w_grad
                self.b -= b_grad

                # 9) 로지스틱 손실함수의 계산 수행
                    # 안전한 로그 계산을 위한 클리핑 수행
                # a = np.clip(a, 1e-10, 1 - 1e-10) - 1st method
                a = np.clip(a, -100, None)
                loss += -(y[i]*np.log(a)+(1-y[i])*np.log(1-a))

            pass # epoch loop (1 epoch)
        
        # 로지스틱 손실 함수의 평균값 계산
        self.losses.append(loss/len(y))

        pass # fit


    # 분류예측함수
    def predict(self, x):
        # 정방향 계산 수행
        z = [ self.forpass(xi)  for xi in x  ]

        # 활성화 함수 통과
        a = self.activation(np.array(z)) # 리스트(내포)로 나온 결과를 벡터로 변환
        
        # 임계함수로 step function을 통과시켜 최종 분류예측값 산출
        return a > .5

        pass # predict

In [0]:
logisticNN = LogisticNeuron()
logisticNN

In [0]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [0]:
x = cancer.data
y = cancer.target
x.shape, y.shape

((569, 30), (569,))

y (정답) : 1-D vector  
x (입력) : 2-D matrix

In [0]:
x[0][:] # 첫 번째 샘플

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [0]:
pp(np.unique(y, return_counts= 1))
m = len(y)

212/m, 357/m

(array([0, 1]), array([212, 357]))


(0.37258347978910367, 0.6274165202108963)

훈련셋과 테스트 셋으로 분할

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# x (입력)
# y (정답)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .2, stratify = y)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape, np.unique(y_test, return_counts=1))


(455, 30) (114, 30)
(455,) (114,) (array([0, 1]), array([42, 72]))


In [0]:
logisticNN.fit(x_train, y_train, epochs = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:86: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:86: RuntimeWarning: invalid value encountered in multiply


AttributeError: ignored

In [0]:
 logisticNN.w

array([ 8.68414600e+03, -5.92038000e+03,  3.45061600e+04,  3.66430000e+03,
       -3.35998000e+00, -4.73725500e+02, -7.50599717e+02, -2.79229379e+02,
       -4.25850000e+01,  1.28916100e+01,  1.72371500e+02, -2.63168500e+02,
       -2.94283780e+03, -9.18605900e+03, -7.32226600e+00, -1.27164872e+02,
       -1.87243594e+02, -4.27042630e+01, -2.79588160e+01, -1.01497117e+01,
        8.81189500e+03, -9.17409000e+03,  1.24203700e+04, -6.87440000e+03,
       -5.84886900e+01, -1.56299474e+03, -2.07543593e+03, -5.35339961e+02,
       -2.40399500e+02, -9.76573000e+01])

In [0]:
logisticNN.b

1156.0000000000011

In [0]:
logisticNN.predict(x_test)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True])

In [0]:
np.mean(  logisticNN.predict(x_test) == y_test  )

0.8421052631578947